Added function to differentiate that the cache needs to be reloaded. Still having error
TimelineTrackDrawingWidget_AnnotationComments.reloadModelFromConfigCache()
Traceback (most recent call last):
  File "/Users/pho/repo/PhoPyQtTimelinePlotter/GUI/TimelineTrackWidgets/TimelineTrackDrawingWidget_AnnotationComments.py", line 249, in on_mouse_moved
    super().on_mouse_moved(event)
  File "/Users/pho/repo/PhoPyQtTimelinePlotter/GUI/TimelineTrackWidgets/TimelineTrackDrawingWidget_SelectionBase.py", line 227, in on_mouse_moved
    self.clear_hover()
  File "/Users/pho/repo/PhoPyQtTimelinePlotter/GUI/TimelineTrackWidgets/TimelineTrackDrawingWidget_SelectionBase.py", line 145, in clear_hover
    self.deemphasize_all()
  File "/Users/pho/repo/PhoPyQtTimelinePlotter/GUI/TimelineTrackWidgets/TimelineTrackDrawingWidget_SelectionBase.py", line 115, in deemphasize_all
    self.durationObjects[prevSelectedItemIndex].set_state_deemphasized()
IndexError: list index out of range
Abort trap: 6
(Py3Qt5) bash-5.0$